// Generated by CoffeeScript 1.9.1
(function() {
  window.Game = (function() {
    var RushGame, p;
    RushGame = function() {
      console.log('Rush game starts.');
      this.canvas = document.getElementById('game-canvas');
      this.stage = new createjs.Stage(this.canvas);
      this.initGame();
      this.updateView();
    };
    p = RushGame.prototype;
    p.initGame = function() {
      var platform;
      platform = new window.Platform();
      platform.x = 100;
      platform.y = 100;
      this.stage.addChild(platform);
    };
    p.updateView = function() {
      this.stage.update();
    };
    return RushGame;
  })();

}).call(this);
