// Generated by CoffeeScript 1.9.1
(function() {
  window.Hero = (function() {
    var Hero, p;
    Hero = function() {
      return this.initialize();
    };
    p = Hero.prototype = new window.MovableGameObject();
    p.MovableGameObject_intialize = p.initialize;
    p.initialize = function() {
      var shape;
      this.MovableGameObject_intialize();
      this.category = 'hero';
      this.width = 10;
      this.height = 16;
      shape = window.CommonShapes.rectangle({
        width: this.width,
        height: this.height,
        fillColor: "#0f0"
      });
      this.addChild(shape);
      this.regX = this.width / 2;
      this.regY = this.height;
      this.collisionPoints = [new createjs.Point(this.regX, this.regY)];
    };
    return Hero;
  })();

}).call(this);
