// Generated by CoffeeScript 1.9.1
(function() {
  window.Coin = (function() {
    var Coin, p;
    Coin = function() {
      this.initialize();
    };
    p = Coin.prototype = new window.GameObject();
    p.category = 'coin';
    p.GameObject_initialize = p.initialize;
    p.initialize = function() {
      var shape;
      this.width = 10;
      this.height = 10;
      shape = window.CommonShapes.rectangle({
        width: this.width,
        height: this.height,
        fillColor: "#ff0"
      });
      this.addChild(shape);
      this.regX = this.width / 2;
      this.regY = this.height;
    };
    return Coin;
  })();

}).call(this);
